### ISSUE TITLE
sentinel-1 sensor model in the paper

### ISSUE THREAD

**Issue by lihengzhong** [centreborelli/rpcfit#4]
could you give some information about the range-doppler physical sensor model of sentinel-1 described in section 4.1?

**Comment by rolandakiki** [comment]
Hello, this model maps the coordinates of a 3D point into the image coordinates and vice-versa. It is well known in the literature and based only on the satellite orbits and some image timing information (both of which are considered metadata, which you need to read properly).  
There is a number of open source software which should handle this, among which:
- [s1tbx](https://github.com/senbox-org/s1tbx/tree/master)
- [sarpy](https://github.com/ngageoint/sarpy)
- [isce](https://github.com/isce-framework/isce2)
- [doris](http://doris.tudelft.nl/)
and others ...
Hope this helps !
